#!/usr/bin/env bash

# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

# Include paths if they exist
paths=("$HOME/bin"
       "$HOME/.local/bin")
for p in "${paths[@]}"; do
    if [ -d "$p" ] ; then
        PATH="$p:$PATH"
    fi
done

if [ -d "$HOME/.local/share/man/" ] ; then
    MANPATH="$HOME/.local/share/man/:$MANPATH"
fi

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
    fi
fi
