#!/usr/bin/env bash
# vi: ft=bash

# Add bin to path always so that ssh command can exec these directly
#export PATH="$HOME/bin/:$PATH"
# This PATH modificatoin will just append to PATH every time. Try to keep PATH
# changes to login script '~/.profile', not for each bash invocation.

# If not running interactively, don't do anything more
[ -z "$PS1" ] && return

export EDITOR=nvim

# Bind ctrl-a to do the opposite of ctrl-z
# This is not recommended way to do this in bash, bindings are not intended to be used this way and
# it can lead to strange behavior and broken tty settings (resetted by `stty sane`)
bind -x '"\C-a":"fg"'

HISTCONTROL=ignoreboth:erasedups
HISTSIZE=10000
HISTFILESIZE=10000
IGNOREEOF=5   # Shell only exists after the 10th consecutive Ctrl-d

shopt -s histappend  # keep bash history on shell exit
shopt -s cmdhist     # save multi-line commands in one history entry
shopt -s checkwinsize  # check window size after each cmd, update LINES COLUMNS
shopt -s globstar  # let "**" expansion match files and 0+ (sub)directories

alias gf='git fetch'
alias gs='git status'
alias gd='git diff'
alias ga='git add -u'

alias woman='MANPAGER="nvim +Man!" man'
alias astronvim='NVIM_APPNAME=astronvim nvim'

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

PS1_chroot="${debian_chroot:+($debian_chroot)}"
if [ "$color_prompt" = yes ]; then
    PS1_dir='\[\033[01;34m\]\w\[\033[00m\]'
else
    PS1_dir='\w'
fi
unset color_prompt
PS1="$PS1_chroot$PS1_dir"'$(__git_ps1 " (%s)")\$ '
export GIT_PS1_SHOWUPSTREAM=verbose

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    if [ -r ~/.dircolors ]; then
        eval "$(dircolors -b ~/.dircolors)"
    else
        eval "$(dircolors -b)"
    fi
    alias ls='ls --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# Find all lines with "property" followed with a line with "memoize" and
# startup vim with the locations in quickfix list:
# Example: git ls-files -z *.py | twogrep property memoize | nvim -c 'cbuffer!'
twogrep() {
  xargs -0 awk '/'"$1"'/ {b=NR+1} NR==b && /'"$2"'/ {print FILENAME "|" FNR "|" $0} '
}

ggblame() {
  git grep -n "$@" | while IFS=: read -r i j _k; do git blame -L "$j,$j" "$i"; done
}

# Use clang as default c/c++ compiler
export CC=clang
export CXX=clang++

# Distributed c and cached build result
export CCACHE_DIR=/local/ccache
export DISTCC_DIR=/local/distcc
export USE_DISTCC=1

# completion for git-jump from git contrib folder
_git_jump() { __gitcomp "diff merge grep ws" "" "$cur"; }

eval "$(direnv hook bash)"
eval "$(zoxide init bash)"

export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"
export CHEZMOI_HOME="$XDG_DATA_HOME/chezmoi"

# fzf
eval "$(fzf --bash)"
source "$XDG_CONFIG_HOME/bash/fzf-bash-completion.sh"
bind -x '"\t": fzf_bash_completion'
#export FZF_DEFAULT_OPTS="--no-mouse $FZF_DEFAULT_OPTS"

# broot (interactive tree explorer)
source "$XDG_CONFIG_HOME/broot/launcher/bash/br"

# changes PS1 to add OSC codes for semantic zones
#if [[ "$TERM_PROGRAM" == "WezTerm" ]]; then
#  source "$XDG_CONFIG_HOME/wezterm/shell-integration.sh"  # This makes my prompt very slow
#fi

[ -e "$HOME/mediatek.bash" ] && source "$HOME/mediatek.bash"

